---
mail: 
pass: 
g_id: 
logintype: lobi
#loginTypeの記述のミスはエラーの原因となります
#Lobiアカウントでのログインは「lobi」
#Twitterアカウントでのログインは「twitter」
#初期値はlobi
switch: true
#シャウトのスイッチ設定
#初期値はtrue(シャウトあり)

x1: 
y1: 
z1: 

x2: 
y2: 
z2: 

x3: 
y3: 
z3: 

x4: 
y4: 
z4: 

x5: 
y5: 
z5: 

x6: 
y6: 
z6:  
...
